import { ALIAS_MAP } from './name-aliases.js';

/**
 * Deterministic skill and language name normalization (SPEC.md §12.2).
 *
 * `name` preserves the human-readable value (trimmed and whitespace-collapsed).
 * `normalizedName` is generated by deterministic application code for matching
 * and deduplication. It is not manually editable.
 */

function normalizeNameInternal(name: string): { name: string; normalizedName: string } {
  const trimmed = name.trim().replace(/\s+/g, ' ');
  const lowercased = trimmed.toLowerCase();
  // NFKD + strip combining diacritics (Unicode category "Mn").
  const stripped = lowercased.normalize('NFKD').replace(/\p{Mn}/gu, '');
  // Remove punctuation separators.
  const cleaned = stripped.replace(/[._\-+/]/g, '');
  const normalizedName = ALIAS_MAP[cleaned] ?? cleaned;
  return { name: trimmed, normalizedName };
}

export function normalizeSkillName(name: string): { name: string; normalizedName: string } {
  return normalizeNameInternal(name);
}

export function normalizeLanguageName(name: string): { name: string; normalizedName: string } {
  return normalizeNameInternal(name);
}
